import type { LicenseStage, RoadTestChecklistSection } from "@prisma/client";

export type RoadTestSeedCategory = {
  slug: string;
  name: string;
  description: string;
  stage: LicenseStage;
  sortOrder: number;
};

export type RoadTestSeedChoice = {
  text: string;
  isCorrect: boolean;
};

export type RoadTestSeedQuestion = {
  stage: LicenseStage;
  sourceReference: string;
  categorySlug: string;
  prompt: string;
  explanation: string;
  choices: RoadTestSeedChoice[];
};

export type RoadTestSeedChecklistItem = {
  stage: LicenseStage;
  section: RoadTestChecklistSection;
  sourceReference: string;
  categorySlug: string;
  title: string;
  description: string;
  sortOrder: number;
};

export const ontarioRoadTestSourceUrls = {
  newDrivers: "https://www.ontario.ca/page/get-g-drivers-licence-new-drivers",
  levelTwoRoadTest: "https://www.ontario.ca/document/official-mto-drivers-handbook/level-two-road-test",
  freewayDriving: "https://www.ontario.ca/document/official-mto-drivers-handbook/freeway-driving",
  changingDirections: "https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions",
  parking: "https://www.ontario.ca/document/official-mto-drivers-handbook/parking-along-roadways",
} as const;

export const ontarioRoadTestSeedCategories: RoadTestSeedCategory[] = [
  {
    slug: "g2-observation-and-right-of-way",
    name: "G2 observation and right-of-way",
    description: "G1-exit road-test decisions: scanning, yielding, intersections, signals, and safe traffic gaps.",
    stage: "G2",
    sortOrder: 110,
  },
  {
    slug: "g2-turns-parking-and-control",
    name: "G2 turns, parking, and control",
    description: "G2 road-test fundamentals: turns, lane changes, roadside stops, parking, speed choice, and smooth control.",
    stage: "G2",
    sortOrder: 120,
  },
  {
    slug: "g2-road-test-readiness",
    name: "G2 road-test readiness",
    description: "What to practise before the G2 road test, including legal eligibility, calm decisions, and common serious errors.",
    stage: "G2",
    sortOrder: 130,
  },
  {
    slug: "g-highway-merging-and-exiting",
    name: "Full G highway merging and exiting",
    description: "G road-test freeway skills: acceleration lanes, safe gaps, freeway spacing, exit planning, and ramp speed.",
    stage: "G",
    sortOrder: 210,
  },
  {
    slug: "g-advanced-lane-and-traffic-flow",
    name: "Full G lane changes and traffic flow",
    description: "Advanced full-G decisions: lane discipline, passing, mirrors, blind spots, speed control, and space management.",
    stage: "G",
    sortOrder: 220,
  },
  {
    slug: "g-road-test-readiness",
    name: "Full G road-test readiness",
    description: "Full-G preparation: route planning, highway comfort, adverse conditions, and self-assessment before booking.",
    stage: "G",
    sortOrder: 230,
  },
];

export const ontarioRoadTestSeedQuestions: RoadTestSeedQuestion[] = [
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#g2-road-test-g1-exit-test`,
    categorySlug: "g2-road-test-readiness",
    prompt: "What is the G2 road test mainly checking after the G1 stage?",
    explanation: "Ontario describes the G2 road test as the G1 exit test. It checks whether a new driver can safely handle basic road-test tasks and make responsible decisions in traffic.",
    choices: [
      { text: "Whether you can safely handle basic driving tasks in traffic", isCorrect: true },
      { text: "Whether you can drive on freeways without supervision", isCorrect: false },
      { text: "Whether you know every mechanical part of the vehicle", isCorrect: false },
      { text: "Whether you can park without ever using mirrors", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#turning-a-corner`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "Before a road-test turn, what should you do before entering the turn?",
    explanation: "The Ontario handbook tells drivers to signal, look side to side, check blind spots, slow before the turn, and enter only when the path is clear.",
    choices: [
      { text: "Signal, scan, check blind spots, slow, and turn only when clear", isCorrect: true },
      { text: "Enter the turn first, then check mirrors", isCorrect: false },
      { text: "Accelerate to finish the turn quickly", isCorrect: false },
      { text: "Watch only the vehicle directly ahead", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#right-turn-on-a-red-light`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "What is required before turning right on a red light where it is permitted?",
    explanation: "A right turn on red requires a complete stop first. You must yield to pedestrians and traffic and proceed only if the way is clear and no sign prohibits the turn.",
    choices: [
      { text: "Stop completely, yield, and turn only when clear and allowed", isCorrect: true },
      { text: "Roll through slowly if cross traffic is light", isCorrect: false },
      { text: "Turn only after the driver behind you honks", isCorrect: false },
      { text: "Ignore pedestrians once they pass your lane", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#changing-lanes`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "What observation habit should be clear during a G2 lane change?",
    explanation: "A safe lane change requires checking traffic, signalling, using mirrors, checking blind spots, and moving only when there is a safe gap.",
    choices: [
      { text: "Mirror check, signal, blind-spot check, then move into a safe gap", isCorrect: true },
      { text: "Signal after entering the next lane", isCorrect: false },
      { text: "Use mirrors only because blind spots are optional", isCorrect: false },
      { text: "Move first so other drivers can react", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#roadside-stop`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "What should you remember during a roadside stop on a road test?",
    explanation: "Roadside stops require choosing a safe place, signalling, checking traffic, stopping close and parallel to the curb or road edge, and checking before opening a door or pulling out.",
    choices: [
      { text: "Signal, choose a safe place, stop close to the edge, and check before moving", isCorrect: true },
      { text: "Stop wherever the examiner asks, even if it blocks traffic", isCorrect: false },
      { text: "Open the door immediately to show you are parked", isCorrect: false },
      { text: "Pull out without signalling if traffic looks far away", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#parallel-parking`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "What is the safest approach to parallel parking on a road test?",
    explanation: "Parallel parking should be controlled and observant: signal, check around the vehicle, reverse slowly, use reference points, and stop without hitting the curb or creating a hazard.",
    choices: [
      { text: "Signal, check around, reverse slowly, and maintain control", isCorrect: true },
      { text: "Reverse quickly so traffic is delayed for less time", isCorrect: false },
      { text: "Ignore vehicles behind once reverse lights are on", isCorrect: false },
      { text: "Mount the curb if it helps straighten the vehicle", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#left-turns`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "When turning left, what should you do before crossing oncoming traffic?",
    explanation: "A left turn must be made from the proper lane after signalling and checking. Yield to oncoming traffic and pedestrians, and turn only when there is a safe gap.",
    choices: [
      { text: "Yield to oncoming traffic and pedestrians until there is a safe gap", isCorrect: true },
      { text: "Assume oncoming traffic will slow for you", isCorrect: false },
      { text: "Begin turning before checking pedestrians", isCorrect: false },
      { text: "Turn wide into any lane that is open", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#booking-a-road-test`,
    categorySlug: "g2-road-test-readiness",
    prompt: "Before booking a G2 road test, what should your practice show?",
    explanation: "A learner should be consistently safe before booking: smooth control, legal stops, proper observation, signalling, yielding, and calm corrections without examiner intervention.",
    choices: [
      { text: "Consistent safe decisions without needing reminders or intervention", isCorrect: true },
      { text: "One lucky perfect route with no traffic", isCorrect: false },
      { text: "Only parking practice, because moving traffic is not tested", isCorrect: false },
      { text: "Confidence even if rules are still uncertain", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#driving-through-roundabouts`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "What should you do when approaching a roundabout?",
    explanation: "At a roundabout, slow down, choose the correct lane, yield to traffic already in the roundabout and to pedestrians, then signal and exit safely.",
    choices: [
      { text: "Slow, choose the correct lane, yield, and exit with care", isCorrect: true },
      { text: "Enter quickly because traffic inside must stop", isCorrect: false },
      { text: "Stop inside the roundabout to decide your exit", isCorrect: false },
      { text: "Change lanes inside without checking", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#parking-on-a-hill`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "Why do hill-parking wheel positions matter on a road test?",
    explanation: "Correct wheel position reduces the chance of a parked vehicle rolling into traffic if the brakes fail. Ontario distinguishes downhill, uphill with a curb, and uphill without a curb.",
    choices: [
      { text: "They help prevent the vehicle from rolling into traffic", isCorrect: true },
      { text: "They make it easier to leave without checking", isCorrect: false },
      { text: "They are only needed for manual transmission vehicles", isCorrect: false },
      { text: "They replace the need for a parking brake", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#what-happens-if-i-fail-a-g1-or-g2-road-test`,
    categorySlug: "g2-road-test-readiness",
    prompt: "What mindset is safest if you make a minor mistake during the G2 test?",
    explanation: "A minor error should be corrected calmly and safely. Do not rush, panic, or make a second unsafe move; continue applying observation, speed control, and right-of-way rules.",
    choices: [
      { text: "Correct calmly and continue making safe legal decisions", isCorrect: true },
      { text: "Speed up to make up lost time", isCorrect: false },
      { text: "Argue with the examiner while driving", isCorrect: false },
      { text: "Ignore mirrors until you feel settled again", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#passing`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "When passing on a two-way road, what must be true before you move out?",
    explanation: "Passing requires a legal passing zone, a clear view, enough distance from oncoming traffic, and enough space to return without cutting off the vehicle passed.",
    choices: [
      { text: "It is legal, clear, and there is enough space to return safely", isCorrect: true },
      { text: "The vehicle ahead is slower than you prefer", isCorrect: false },
      { text: "You can see only partway over a hill", isCorrect: false },
      { text: "You plan to return immediately in front of the other vehicle", isCorrect: false },
    ],
  },

  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#turning-a-corner`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "How should your speed change before making a right or left turn on the G2 test?",
    explanation: "Slow before entering the turn, keep the vehicle under control through the turn, and accelerate only after the vehicle is straight and the path is safe.",
    choices: [
      { text: "Slow before the turn, control the vehicle, then accelerate when safe", isCorrect: true },
      { text: "Brake halfway through every turn", isCorrect: false },
      { text: "Accelerate into the turn to clear traffic quickly", isCorrect: false },
      { text: "Coast through without checking speed", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#turning-a-corner`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "Why should you scan left, centre, and right before entering an intersection?",
    explanation: "Scanning the whole intersection helps you notice pedestrians, cyclists, turning vehicles, red-light runners, and other hazards before you commit to moving through.",
    choices: [
      { text: "To confirm the full intersection path is clear before you enter", isCorrect: true },
      { text: "To avoid using your mirrors at intersections", isCorrect: false },
      { text: "To show the examiner you can turn your head quickly", isCorrect: false },
      { text: "To decide whether the speed limit still applies", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#left-turns`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "What should you do if your view is blocked while waiting to turn left?",
    explanation: "If you cannot see enough to judge a safe gap, wait. A blocked view is not a reason to guess or force a turn across oncoming traffic or pedestrians.",
    choices: [
      { text: "Wait until you can see clearly and the gap is safe", isCorrect: true },
      { text: "Follow the vehicle ahead without checking", isCorrect: false },
      { text: "Move into oncoming traffic to make others stop", isCorrect: false },
      { text: "Turn because hesitation always fails the test", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#left-turns`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "Which lane should you normally enter after a left turn onto a multi-lane road?",
    explanation: "A left turn should normally finish in the lane closest to the centre line or median, unless lane markings, signs, or examiner instructions direct otherwise.",
    choices: [
      { text: "The lane closest to the centre line or median", isCorrect: true },
      { text: "Any lane that has the fewest vehicles", isCorrect: false },
      { text: "The far-right lane every time", isCorrect: false },
      { text: "The shoulder until traffic clears", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#turning-a-corner`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "Why is a wide turn a problem on a G2 road test?",
    explanation: "A wide turn can enter the wrong lane, surprise nearby drivers, create a conflict with cyclists or pedestrians, and show poor lane control.",
    choices: [
      { text: "It can put the vehicle into the wrong lane or create a conflict", isCorrect: true },
      { text: "It proves you are checking more of the road", isCorrect: false },
      { text: "It is required whenever traffic is heavy", isCorrect: false },
      { text: "It replaces the need for a signal", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#right-turn-on-a-red-light`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "What should you check for before a right turn on red after stopping?",
    explanation: "After the complete stop, check signs, pedestrians, cyclists, and traffic from the left and from the direction you are entering before turning only when safe.",
    choices: [
      { text: "Signs, pedestrians, cyclists, and traffic before turning when clear", isCorrect: true },
      { text: "Only the traffic light colour", isCorrect: false },
      { text: "Only the driver waiting behind you", isCorrect: false },
      { text: "Only vehicles in your current lane", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#changing-lanes`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "When should you cancel a planned lane change on the road test?",
    explanation: "Cancel the lane change if the gap closes, another driver speeds up, a vehicle enters your blind spot, or any condition makes the move unsafe.",
    choices: [
      { text: "When the gap or conditions are no longer safe", isCorrect: true },
      { text: "Never, because cancelling looks uncertain", isCorrect: false },
      { text: "Only after you have crossed the lane line", isCorrect: false },
      { text: "Only if the examiner tells you to cancel", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#changing-lanes`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "What should your steering feel like during a G2 lane change?",
    explanation: "A safe lane change is smooth and controlled. Do not jerk the wheel, drift, brake suddenly, or force other drivers to react sharply.",
    choices: [
      { text: "Smooth, controlled, and matched to a safe gap", isCorrect: true },
      { text: "Fast and abrupt so the lane change ends quickly", isCorrect: false },
      { text: "A slow drift without signalling", isCorrect: false },
      { text: "A hard brake followed by a sharp turn", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#passing`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "Why must you check road markings before passing on a two-way road?",
    explanation: "Road markings show whether passing is legal. Even with good visibility, you should not pass where signs or pavement markings prohibit it.",
    choices: [
      { text: "They help show whether passing is legally allowed", isCorrect: true },
      { text: "They tell you the vehicle ahead must slow down", isCorrect: false },
      { text: "They replace the need to check oncoming traffic", isCorrect: false },
      { text: "They let you pass on hills and curves", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#driving-through-roundabouts`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "Who should you yield to before entering a roundabout?",
    explanation: "Before entering a roundabout, yield to pedestrians and to traffic already circulating in the roundabout, then enter when there is a safe gap.",
    choices: [
      { text: "Pedestrians and traffic already in the roundabout", isCorrect: true },
      { text: "Only drivers behind your vehicle", isCorrect: false },
      { text: "Only vehicles entering after you", isCorrect: false },
      { text: "No one, because entering traffic has priority", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#driving-through-roundabouts`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "What should you do before leaving a roundabout?",
    explanation: "Signal your exit, keep scanning for pedestrians and cyclists, and leave from the correct lane without stopping suddenly inside the roundabout.",
    choices: [
      { text: "Signal the exit and check for pedestrians and cyclists", isCorrect: true },
      { text: "Stop inside the circle to check your route", isCorrect: false },
      { text: "Change lanes at the exit without signalling", isCorrect: false },
      { text: "Speed up because exiting traffic has no conflicts", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#roadside-stop`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "Before pulling away from a roadside stop, what sequence should be obvious?",
    explanation: "Before re-entering traffic, signal, check mirrors, check the blind spot, confirm a safe gap, then move out smoothly without cutting off traffic.",
    choices: [
      { text: "Signal, mirror check, blind-spot check, safe gap, then move", isCorrect: true },
      { text: "Move first, then signal if another vehicle appears", isCorrect: false },
      { text: "Use hazard lights instead of checking traffic", isCorrect: false },
      { text: "Pull out quickly because parked vehicles have priority", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#roadside-stop`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "Where should you avoid making a roadside stop on a road test?",
    explanation: "Choose a safe legal place. Avoid blocking traffic, stopping too close to intersections or driveways, or stopping where signs, visibility, or road conditions make it unsafe.",
    choices: [
      { text: "Anywhere unsafe, illegal, or blocking traffic", isCorrect: true },
      { text: "Only in places with no curb", isCorrect: false },
      { text: "Only on roads with parked cars", isCorrect: false },
      { text: "Anywhere the examiner can see the curb", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#parallel-parking`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "What should you do if another road user approaches while you are parallel parking?",
    explanation: "Keep checking around the vehicle, pause if needed, communicate with signals or brake lights, and continue only when it is safe and controlled.",
    choices: [
      { text: "Keep checking, pause if needed, and continue only when safe", isCorrect: true },
      { text: "Reverse faster before they arrive", isCorrect: false },
      { text: "Ignore them because you are already parking", isCorrect: false },
      { text: "Wave them around without checking your blind spot", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#parking-on-a-hill`,
    categorySlug: "g2-road-test-readiness",
    prompt: "What should accompany the correct wheel position when hill parking?",
    explanation: "Hill parking also requires a secure stop: select a legal position, set the parking brake, put the vehicle in the correct gear or park, and check before leaving or moving.",
    choices: [
      { text: "A secure stop with the parking brake and safe checks", isCorrect: true },
      { text: "Leaving the vehicle in neutral", isCorrect: false },
      { text: "Turning off the signal before stopping", isCorrect: false },
      { text: "Relying only on the curb to hold the vehicle", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#g2-road-test-g1-exit-test`,
    categorySlug: "g2-road-test-readiness",
    prompt: "What kind of driving environment should a G2 candidate practise before test day?",
    explanation: "A ready G2 candidate should practise in real traffic conditions similar to the test: intersections, turns, lane changes, parking tasks, pedestrians, and varying speeds.",
    choices: [
      { text: "Realistic routes with traffic, turns, lane changes, and parking tasks", isCorrect: true },
      { text: "Only empty parking lots", isCorrect: false },
      { text: "Only one memorized route at one time of day", isCorrect: false },
      { text: "Only highway driving at full speed", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#booking-a-road-test`,
    categorySlug: "g2-road-test-readiness",
    prompt: "Why should you avoid booking the G2 test before observation habits are automatic?",
    explanation: "Observation is used constantly on the test. If mirror checks, blind-spot checks, and intersection scans require reminders, the driver is not consistently ready for independent traffic decisions.",
    choices: [
      { text: "Because safe observation must be consistent without reminders", isCorrect: true },
      { text: "Because observation is checked only during parking", isCorrect: false },
      { text: "Because the examiner will teach observation during the test", isCorrect: false },
      { text: "Because blind-spot checks are optional after the G1", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#what-happens-if-i-fail-a-g1-or-g2-road-test`,
    categorySlug: "g2-road-test-readiness",
    prompt: "What should you do if the examiner gives an instruction late or traffic changes suddenly?",
    explanation: "Safety comes first. If following an instruction immediately would be unsafe, continue legally and safely, then follow the next safe opportunity or instruction.",
    choices: [
      { text: "Choose the safe legal action instead of forcing the instruction", isCorrect: true },
      { text: "Cut across lanes so you do not miss the instruction", isCorrect: false },
      { text: "Stop suddenly in traffic to ask for clarification", isCorrect: false },
      { text: "Ignore all later instructions", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#turning-a-corner`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "Why should you check the crosswalk before completing a turn?",
    explanation: "Pedestrians and cyclists may be crossing at the road you are entering. The driver must yield and should not turn into a crosswalk conflict.",
    choices: [
      { text: "To avoid turning into pedestrians or cyclists crossing your path", isCorrect: true },
      { text: "To decide whether signalling is necessary", isCorrect: false },
      { text: "To see if the examiner is watching", isCorrect: false },
      { text: "To avoid checking oncoming traffic", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#changing-lanes`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "What does a blind-spot check add that mirrors alone may miss?",
    explanation: "Mirrors do not show every area beside the vehicle. A shoulder check helps confirm that no vehicle, cyclist, or motorcycle is hidden before you move.",
    choices: [
      { text: "It confirms no road user is hidden beside the vehicle", isCorrect: true },
      { text: "It replaces signalling", isCorrect: false },
      { text: "It lets you ignore traffic ahead", isCorrect: false },
      { text: "It is only needed at night", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#changing-lanes`,
    categorySlug: "g2-road-test-readiness",
    prompt: "How can you show confidence without rushing during a G2 test?",
    explanation: "Confident driving is calm and predictable: plan early, keep safe speed, observe fully, signal in time, and wait for legal safe gaps instead of hesitating late or rushing.",
    choices: [
      { text: "Plan early, observe fully, and move only into safe legal gaps", isCorrect: true },
      { text: "Move quickly so the examiner sees confidence", isCorrect: false },
      { text: "Avoid signalling so choices are flexible", isCorrect: false },
      { text: "Wait at every intersection even when you have right-of-way", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#parking-along-roadways`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "What should you confirm before opening a door after parking at the roadside?",
    explanation: "Check for traffic, cyclists, and pedestrians before opening a door. Opening a door into another road user's path creates a hazard.",
    choices: [
      { text: "That no vehicle, cyclist, or pedestrian is approaching beside you", isCorrect: true },
      { text: "That the examiner has already removed the seat belt", isCorrect: false },
      { text: "That your front wheels are straight in every parking situation", isCorrect: false },
      { text: "That traffic behind you is moving quickly", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#left-turns`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "What should you do if an oncoming vehicle is close while you wait to turn left?",
    explanation: "Yield and wait. A safe left turn needs enough time and distance to clear the intersection without causing oncoming traffic to brake or swerve.",
    choices: [
      { text: "Yield until there is enough time and distance to turn safely", isCorrect: true },
      { text: "Begin turning so the oncoming driver slows", isCorrect: false },
      { text: "Focus only on the traffic light", isCorrect: false },
      { text: "Turn halfway and stop in the oncoming lane", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#turning-a-corner`,
    categorySlug: "g2-turns-parking-and-control",
    prompt: "Why should you keep both hands ready on the wheel during test manoeuvres?",
    explanation: "Good steering control helps the vehicle stay in the correct lane, recover smoothly after turns, and avoid overcorrection during parking, lane changes, or roadside stops.",
    choices: [
      { text: "It supports smooth control and correct lane position", isCorrect: true },
      { text: "It removes the need for speed control", isCorrect: false },
      { text: "It proves you can turn without checking mirrors", isCorrect: false },
      { text: "It lets you ignore road surface conditions", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#parallel-parking`,
    categorySlug: "g2-road-test-readiness",
    prompt: "What is a good sign that parking practice is test-ready?",
    explanation: "Test-ready parking is repeatable: full observation, correct signalling, slow controlled movement, legal final position, and safe re-entry without curb hits or panic corrections.",
    choices: [
      { text: "You can park repeatedly with observation, control, and legal position", isCorrect: true },
      { text: "You can park once if no one else is nearby", isCorrect: false },
      { text: "You can park only with verbal coaching", isCorrect: false },
      { text: "You can stop crooked as long as it is quick", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#passing`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "What should you do if you start a pass but conditions become unsafe?",
    explanation: "Do not force the pass. Ease off, return to a safe following position when possible, and wait for a legal clear opportunity rather than cutting off another vehicle.",
    choices: [
      { text: "Abort safely and return to a safe following position when possible", isCorrect: true },
      { text: "Speed up no matter what because you already started", isCorrect: false },
      { text: "Force the other driver to brake", isCorrect: false },
      { text: "Drive on the shoulder until there is room", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#g2-road-test-g1-exit-test`,
    categorySlug: "g2-road-test-readiness",
    prompt: "What is the best way to treat examiner feedback after a failed or weak mock G2 test?",
    explanation: "Use the feedback to practise the specific weak skills, such as observation, turns, parking, speed control, or yielding, before booking or retesting.",
    choices: [
      { text: "Practise the specific weak skills until they are consistent", isCorrect: true },
      { text: "Book again immediately without changing practice", isCorrect: false },
      { text: "Ignore the comments if you felt confident", isCorrect: false },
      { text: "Practise only the easiest route", isCorrect: false },
    ],
  },
  {
    stage: "G2",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#turning-a-corner`,
    categorySlug: "g2-observation-and-right-of-way",
    prompt: "What should you do if a pedestrian starts crossing as you prepare to turn?",
    explanation: "Yield and wait until the pedestrian is safely clear of your path. A G2 road-test turn should never pressure or cut off someone crossing the road.",
    choices: [
      { text: "Yield and wait until the pedestrian is safely clear", isCorrect: true },
      { text: "Turn quickly before the pedestrian reaches your lane", isCorrect: false },
      { text: "Honk so the pedestrian stops", isCorrect: false },
      { text: "Continue if the traffic light is green", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "What is the G road test looking for when you enter a freeway?",
    explanation: "The Level Two road test includes freeway driving. Entering safely means using the acceleration lane, matching traffic speed where safe, signalling, checking mirrors and blind spots, and merging into a safe gap.",
    choices: [
      { text: "Build speed, signal, check mirrors and blind spots, and merge into a safe gap", isCorrect: true },
      { text: "Stop at the end of the acceleration lane every time", isCorrect: false },
      { text: "Merge slowly so freeway traffic can easily see you", isCorrect: false },
      { text: "Enter first, then check for vehicles around you", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#driving-along-a-freeway`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "Why should full-G candidates keep a large space cushion on freeways?",
    explanation: "Freeway speeds reduce reaction time. Keeping space ahead, behind, and beside your vehicle gives you time to respond and avoids cutting off other vehicles during lane changes or merges.",
    choices: [
      { text: "Higher speeds need more reaction time and room for safe decisions", isCorrect: true },
      { text: "It lets you ignore the speed limit", isCorrect: false },
      { text: "It means mirror checks are no longer needed", isCorrect: false },
      { text: "It is needed only when roads are empty", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#lane-change`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "During a full-G lane change, what should the examiner clearly see?",
    explanation: "The Level Two road test includes lane changes. The examiner should see planning, mirror checks, signalling, blind-spot checks, speed control, and a smooth move into a safe gap.",
    choices: [
      { text: "Plan, mirror check, signal, blind-spot check, and move smoothly", isCorrect: true },
      { text: "A fast move before signalling so traffic cannot block you", isCorrect: false },
      { text: "A lane change based only on the rear-view mirror", isCorrect: false },
      { text: "A sudden brake before every lane change", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "How should you leave a freeway during the G test?",
    explanation: "Leaving a freeway safely means planning ahead, signalling, moving to the exit lane early, maintaining control, and reducing speed on the deceleration lane or ramp rather than surprising through traffic.",
    choices: [
      { text: "Plan early, signal, enter the exit lane safely, and slow on the ramp", isCorrect: true },
      { text: "Brake hard in the through lane as soon as you see the exit", isCorrect: false },
      { text: "Cross several lanes at the last second", isCorrect: false },
      { text: "Reverse on the shoulder if you miss the exit", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#driving-along-a-freeway`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "During full-G freeway driving, which lane should slower traffic generally use?",
    explanation: "Ontario's freeway-driving guidance directs slower traffic to keep right. The left lane is generally for passing or faster traffic where permitted by signs and conditions.",
    choices: [
      { text: "The right lane", isCorrect: true },
      { text: "The far-left lane at all times", isCorrect: false },
      { text: "The shoulder", isCorrect: false },
      { text: "Whichever lane has the most traffic", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#business-section`,
    categorySlug: "g-road-test-readiness",
    prompt: "Why does the full-G test include business and residential sections?",
    explanation: "The Level Two road test includes different traffic environments so the examiner can see speed choice, scanning, lane position, yielding, and hazard response in real-world conditions.",
    choices: [
      { text: "To check safe decisions across different traffic environments", isCorrect: true },
      { text: "To avoid testing freeway skills", isCorrect: false },
      { text: "To test only parking-lot steering", isCorrect: false },
      { text: "To let drivers choose any speed that feels comfortable", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#passing`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "What makes a pass or lane change unsafe on a higher-speed road?",
    explanation: "It is unsafe to cut off another vehicle, move without a clear gap, fail to signal or check blind spots, or pass when the view and legal markings do not allow it.",
    choices: [
      { text: "Moving without a legal clear gap and proper observation", isCorrect: true },
      { text: "Waiting for a larger space cushion", isCorrect: false },
      { text: "Cancelling a lane change when conditions change", isCorrect: false },
      { text: "Keeping right when not passing", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#g-road-test-g2-exit-test`,
    categorySlug: "g-road-test-readiness",
    prompt: "What should a G2 driver be comfortable with before booking the full G road test?",
    explanation: "Ontario's full G road test is the G2 exit test and includes more advanced driving, including freeway skills where available. Candidates should be comfortable with city and highway decisions before booking.",
    choices: [
      { text: "Consistent city and highway decisions without unsafe prompts", isCorrect: true },
      { text: "Only quiet residential routes", isCorrect: false },
      { text: "Freeway merging for the first time during the test", isCorrect: false },
      { text: "Relying on the examiner to announce every hazard", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#leaving-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "Why is planning ahead for a freeway exit important?",
    explanation: "Planning early gives you time to signal, check mirrors and blind spots, move to the correct lane, and reduce speed on the ramp without surprising drivers behind you.",
    choices: [
      { text: "It prevents sudden lane changes or braking near the exit", isCorrect: true },
      { text: "It lets you ignore ramp advisory speeds", isCorrect: false },
      { text: "It means you can cross multiple lanes at the gore", isCorrect: false },
      { text: "It removes the need to signal", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#roadside-stop`,
    categorySlug: "g-road-test-readiness",
    prompt: "What does a roadside stop show on the Level Two road test?",
    explanation: "A roadside stop checks observation, signalling, safe positioning, smooth stopping, and safe re-entry into traffic. It is not just a parking task.",
    choices: [
      { text: "Observation, signalling, safe position, control, and re-entry", isCorrect: true },
      { text: "Only whether the wheels touch the curb", isCorrect: false },
      { text: "How quickly you can stop without checking", isCorrect: false },
      { text: "Whether you can block a lane briefly", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#entering-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "If freeway traffic is heavy, what should you do while merging?",
    explanation: "Use the acceleration lane to look for a safe gap, signal, adjust speed smoothly, and merge without forcing another driver to brake sharply or swerve.",
    choices: [
      { text: "Signal, adjust speed smoothly, and merge into a safe gap", isCorrect: true },
      { text: "Force your way in because ramp traffic has priority", isCorrect: false },
      { text: "Stop suddenly in the live lane", isCorrect: false },
      { text: "Drive on the shoulder until traffic clears", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#what-happens-if-i-fail-a-g1-or-g2-road-test`,
    categorySlug: "g-road-test-readiness",
    prompt: "What is the safest response if you miss an instruction or exit during the full G test?",
    explanation: "Stay calm and legal. Do not make a sudden unsafe lane change, stop, or reverse; continue safely and follow the examiner's next instruction.",
    choices: [
      { text: "Continue safely and wait for the next legal instruction", isCorrect: true },
      { text: "Cut across lanes immediately to recover", isCorrect: false },
      { text: "Stop on the freeway shoulder to ask what to do", isCorrect: false },
      { text: "Reverse if you have just passed the exit", isCorrect: false },
    ],
  },

  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#entering-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "What should you do before reaching the end of a freeway acceleration lane?",
    explanation: "Use the acceleration lane to build an appropriate speed, keep scanning traffic, signal, check mirrors and blind spots, and choose a safe gap before the lane ends.",
    choices: [
      { text: "Build speed, observe fully, signal, and choose a safe gap early", isCorrect: true },
      { text: "Wait until the lane ends before checking traffic", isCorrect: false },
      { text: "Stop at the merge point unless traffic waves you in", isCorrect: false },
      { text: "Enter the freeway first and then signal", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#entering-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "Why is matching freeway traffic speed important when merging?",
    explanation: "A smooth merge depends on speed matching where safe. Entering much slower than traffic can force other drivers to brake or swerve, while excessive speed reduces control.",
    choices: [
      { text: "It helps you merge smoothly without forcing traffic to react sharply", isCorrect: true },
      { text: "It gives merging vehicles automatic priority over freeway traffic", isCorrect: false },
      { text: "It means blind-spot checks are no longer needed", isCorrect: false },
      { text: "It lets you ignore the posted speed limit", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#entering-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "What should you do if there is no safe freeway gap right away?",
    explanation: "Keep signalling, continue observing, adjust speed smoothly within the lane, and merge only when a safe gap appears. Do not force traffic to make room suddenly.",
    choices: [
      { text: "Adjust speed smoothly and wait for a safe gap", isCorrect: true },
      { text: "Force another driver to brake because the ramp is ending", isCorrect: false },
      { text: "Stop in the live freeway lane", isCorrect: false },
      { text: "Drive onto the shoulder as your normal merge plan", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#leaving-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "When should you move toward the correct lane for a freeway exit?",
    explanation: "Plan early enough to signal, check, and make each lane change safely. Waiting until the exit is close can cause rushed braking or unsafe multi-lane moves.",
    choices: [
      { text: "Early enough to make each lane change safely and predictably", isCorrect: true },
      { text: "Only after passing the exit sign at the ramp", isCorrect: false },
      { text: "At the last second so the route is shorter", isCorrect: false },
      { text: "After slowing sharply in the through lane", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#leaving-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "Where should most of your speed reduction happen when exiting a freeway?",
    explanation: "After entering the deceleration lane or ramp, reduce speed smoothly for the ramp conditions. Heavy braking in the through lane can surprise fast-moving traffic behind you.",
    choices: [
      { text: "In the deceleration lane or ramp after moving out of through traffic", isCorrect: true },
      { text: "In the centre freeway lane before signalling", isCorrect: false },
      { text: "Only after stopping at the end of the ramp", isCorrect: false },
      { text: "On the shoulder before the exit lane begins", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#leaving-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "What should you do if you realize you are about to miss your freeway exit?",
    explanation: "Continue safely and follow the next legal route. A missed exit is less serious than a sudden lane change, hard brake, shoulder drive, or reverse movement near freeway traffic.",
    choices: [
      { text: "Continue safely and take the next legal route", isCorrect: true },
      { text: "Cross the gore area if the ramp is still visible", isCorrect: false },
      { text: "Brake hard and cut across lanes", isCorrect: false },
      { text: "Reverse carefully on the shoulder", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "Why should freeway merge checks continue after you enter the lane?",
    explanation: "After merging, traffic around you can still change quickly. Recheck mirrors, stabilize speed, and rebuild following distance so the vehicle settles safely into the traffic flow.",
    choices: [
      { text: "To stabilize speed and spacing after joining fast traffic", isCorrect: true },
      { text: "To decide whether the signal was necessary", isCorrect: false },
      { text: "To let you drift into another lane immediately", isCorrect: false },
      { text: "To avoid looking ahead", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "What is a safe response to a short freeway entrance ramp on the G test?",
    explanation: "A short ramp requires earlier scanning and smoother speed judgment. Signal, check, build speed as safely as possible, and choose a gap without abrupt steering or forcing traffic.",
    choices: [
      { text: "Scan early, signal, build suitable speed, and merge only when safe", isCorrect: true },
      { text: "Enter at very low speed because the ramp is short", isCorrect: false },
      { text: "Use abrupt steering so you do not run out of lane", isCorrect: false },
      { text: "Ignore the blind spot because there is less time", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "How should you handle ramp advisory speeds during the full G test?",
    explanation: "Ramp signs and conditions help you choose a controlled speed. Slow smoothly on the ramp and adjust for curve, traffic, weather, and visibility without abrupt braking.",
    choices: [
      { text: "Use the advisory and conditions to choose a controlled ramp speed", isCorrect: true },
      { text: "Keep freeway speed through every ramp", isCorrect: false },
      { text: "Brake only after the ramp curve ends", isCorrect: false },
      { text: "Treat advisory signs as instructions to accelerate", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#driving-along-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    prompt: "What should you do when another vehicle is entering from a ramp near you?",
    explanation: "Maintain awareness and space. If safe and legal, adjust speed or lane position to avoid conflict, but do not make an unsafe lane change just to be polite.",
    choices: [
      { text: "Keep space and adjust safely without creating a new hazard", isCorrect: true },
      { text: "Always brake hard to let the ramp vehicle enter", isCorrect: false },
      { text: "Always change lanes without checking", isCorrect: false },
      { text: "Speed up to block the merge", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#driving-along-a-freeway`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "When is the left freeway lane usually the right choice?",
    explanation: "The left lane is generally for passing or following lane-control signs. A full-G driver should return to an appropriate lane after passing and avoid cruising unnecessarily in the passing lane.",
    choices: [
      { text: "When passing or when signs and traffic conditions make it appropriate", isCorrect: true },
      { text: "Whenever you want the smoothest pavement", isCorrect: false },
      { text: "At all times because it is the safest lane", isCorrect: false },
      { text: "Only when you are driving below traffic speed", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#driving-along-a-freeway`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "What should guide your following distance on a freeway?",
    explanation: "Following distance should increase with speed, poor weather, heavy traffic, and limited visibility. At freeway speeds, tailgating leaves too little time to respond.",
    choices: [
      { text: "Speed, traffic, weather, visibility, and your reaction time", isCorrect: true },
      { text: "How close the driver behind you is following", isCorrect: false },
      { text: "The minimum gap needed to prevent another car entering", isCorrect: false },
      { text: "Only the posted speed limit sign", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#driving-along-a-freeway`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "Why should you avoid driving beside another vehicle for too long?",
    explanation: "Staying beside another vehicle can leave both drivers with fewer escape options. Adjust speed when safe so you are not trapped in another driver's blind spot or boxed in.",
    choices: [
      { text: "It reduces blind-spot risk and preserves escape space", isCorrect: true },
      { text: "It lets you avoid checking mirrors", isCorrect: false },
      { text: "It is required only in parking lots", isCorrect: false },
      { text: "It means you should always speed far ahead", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#changing-lanes`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "What should happen before every full-G lane change in heavier traffic?",
    explanation: "Plan early, check mirrors, signal, shoulder-check the blind spot, confirm the gap remains safe, and move smoothly without making another driver brake sharply.",
    choices: [
      { text: "Plan, mirror check, signal, shoulder-check, confirm the gap, then move", isCorrect: true },
      { text: "Signal only after half the vehicle is in the next lane", isCorrect: false },
      { text: "Move when the front bumper fits, even if the gap is closing", isCorrect: false },
      { text: "Use speed alone instead of observation", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#changing-lanes`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "What should you do if a vehicle enters your blind spot during a planned lane change?",
    explanation: "Cancel or delay the lane change, keep your lane, and choose another safe gap. Forcing the move after the shoulder check finds a vehicle creates an avoidable conflict.",
    choices: [
      { text: "Cancel or delay the lane change and stay in your lane", isCorrect: true },
      { text: "Move faster so you get ahead of the vehicle", isCorrect: false },
      { text: "Keep moving because your signal gives priority", isCorrect: false },
      { text: "Brake hard in your lane without checking behind", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#passing`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "What should you confirm before passing a slower vehicle on a rural road?",
    explanation: "Passing requires a legal passing area, clear view, enough distance from oncoming traffic, and enough space to return without cutting off the vehicle being passed.",
    choices: [
      { text: "Legal markings, clear view, safe oncoming gap, and return space", isCorrect: true },
      { text: "Only that your vehicle can accelerate quickly", isCorrect: false },
      { text: "Only that the driver ahead is below the speed limit", isCorrect: false },
      { text: "That the shoulder is wide enough if something changes", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#passing`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "Why should you return from a pass only after seeing the passed vehicle clearly?",
    explanation: "Returning too early can cut off the vehicle you passed. A safe return leaves enough space so the other driver does not need to brake or swerve.",
    choices: [
      { text: "To leave enough space and avoid cutting off the passed vehicle", isCorrect: true },
      { text: "To avoid using your turn signal", isCorrect: false },
      { text: "To stay in the oncoming lane longer than needed", isCorrect: false },
      { text: "To make the examiner look behind you", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#changing-lanes`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "What does smooth speed control show during full-G traffic flow?",
    explanation: "Smooth speed control shows that you can match traffic, maintain safe spacing, and anticipate changes without repeated hard braking or sudden acceleration.",
    choices: [
      { text: "You can match traffic and preserve space without abrupt moves", isCorrect: true },
      { text: "You can ignore vehicles behind you", isCorrect: false },
      { text: "You are allowed to exceed the speed limit to keep up", isCorrect: false },
      { text: "You do not need lane-position checks", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#business-section`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "What should change when moving from freeway traffic into a business area?",
    explanation: "Business areas require lower speed, more frequent scanning, attention to driveways, pedestrians, cyclists, parked vehicles, signs, and changing lane or turn demands.",
    choices: [
      { text: "Reduce speed and increase scanning for local hazards", isCorrect: true },
      { text: "Keep freeway following distance but ignore pedestrians", isCorrect: false },
      { text: "Stay at ramp speed until the examiner warns you", isCorrect: false },
      { text: "Focus only on lane markings", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#residential-section`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    prompt: "What should a full-G driver watch for in residential sections?",
    explanation: "Residential driving calls for speed control and scanning for pedestrians, cyclists, children, parked vehicles, driveways, stop signs, and limited sight lines.",
    choices: [
      { text: "Pedestrians, cyclists, parked vehicles, driveways, signs, and sight lines", isCorrect: true },
      { text: "Only freeway-style lane changes", isCorrect: false },
      { text: "Only vehicles directly behind you", isCorrect: false },
      { text: "Nothing different from an empty highway", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#g-road-test-g2-exit-test`,
    categorySlug: "g-road-test-readiness",
    prompt: "What practice mix best prepares a learner for the full G road test?",
    explanation: "The full G test checks advanced skills in varied conditions. Practise freeway merging and exits, lane changes, business and residential driving, speed choice, and calm route recovery.",
    choices: [
      { text: "A mix of highway, city, lane-change, spacing, and recovery practice", isCorrect: true },
      { text: "Only the exact road-test centre route", isCorrect: false },
      { text: "Only empty residential streets", isCorrect: false },
      { text: "Only parking manoeuvres already learned for G2", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#g-road-test-g2-exit-test`,
    categorySlug: "g-road-test-readiness",
    prompt: "How should you decide whether you are ready to book the full G test?",
    explanation: "You should be consistently safe without coaching in highway and city traffic. If merging, lane changes, spacing, or exits still need reminders, practise more before booking.",
    choices: [
      { text: "Book when highway and city decisions are consistent without coaching", isCorrect: true },
      { text: "Book as soon as the minimum waiting period ends", isCorrect: false },
      { text: "Book before practising freeway driving so the test is realistic", isCorrect: false },
      { text: "Book when parking alone feels easy", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#freeway`,
    categorySlug: "g-road-test-readiness",
    prompt: "What should a mock full-G highway drive include?",
    explanation: "A useful mock drive includes entrance ramp scanning, speed matching, merge, freeway spacing, lane changes, exit planning, ramp speed, and post-exit city driving.",
    choices: [
      { text: "Merge, spacing, lane changes, exit planning, ramp speed, and city recovery", isCorrect: true },
      { text: "Only driving straight in the right lane", isCorrect: false },
      { text: "Only entering the freeway and stopping afterward", isCorrect: false },
      { text: "Only reading the route before driving", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#what-happens-if-i-fail-a-g1-or-g2-road-test`,
    categorySlug: "g-road-test-readiness",
    prompt: "What should you do with feedback from a weak full-G mock test?",
    explanation: "Use feedback to target specific skills such as merging speed, blind-spot checks, following distance, ramp speed, route recovery, or business-area scanning before retesting.",
    choices: [
      { text: "Practise the exact weak skills until they are repeatable", isCorrect: true },
      { text: "Ignore it if the freeway portion felt exciting", isCorrect: false },
      { text: "Book immediately while the route is still familiar", isCorrect: false },
      { text: "Practise only quiet streets afterward", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#g-road-test-g2-exit-test`,
    categorySlug: "g-road-test-readiness",
    prompt: "Why is calm route recovery important on the full G test?",
    explanation: "Advanced driving includes adapting safely when traffic or instructions change. Continuing legally is better than sudden braking, unsafe lane changes, or trying to force a missed turn.",
    choices: [
      { text: "It shows you can adapt legally without sudden unsafe moves", isCorrect: true },
      { text: "It proves you know every possible road-test route", isCorrect: false },
      { text: "It lets you ignore the examiner's next instruction", isCorrect: false },
      { text: "It means stopping anywhere is acceptable", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#business-section`,
    categorySlug: "g-road-test-readiness",
    prompt: "What makes business-area driving different from the freeway part of the full G test?",
    explanation: "Business areas add frequent intersections, parked vehicles, pedestrians, cyclists, signs, entrances, and speed changes. The examiner can see whether your scanning adapts after highway driving.",
    choices: [
      { text: "More local hazards, lower speeds, and frequent scanning demands", isCorrect: true },
      { text: "No need to check mirrors because speeds are lower", isCorrect: false },
      { text: "Only ramp-speed control matters", isCorrect: false },
      { text: "Lane position no longer matters", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#residential-section`,
    categorySlug: "g-road-test-readiness",
    prompt: "Why should full-G practice include residential driving after highway practice?",
    explanation: "The Level Two test can include residential sections. A driver must show they can transition from highway speeds to careful neighbourhood scanning and speed control.",
    choices: [
      { text: "It proves you can transition to lower-speed hazard scanning", isCorrect: true },
      { text: "It replaces freeway practice", isCorrect: false },
      { text: "It removes the need for stop-sign routines", isCorrect: false },
      { text: "It is useful only for parking tests", isCorrect: false },
    ],
  },
  {
    stage: "G",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#driving-along-a-freeway`,
    categorySlug: "g-road-test-readiness",
    prompt: "What is a good readiness sign for freeway following distance?",
    explanation: "A ready full-G driver keeps enough space consistently, even when traffic speed changes, rather than drifting into tailgating or repeatedly braking late.",
    choices: [
      { text: "You maintain space consistently as traffic speed changes", isCorrect: true },
      { text: "You can stay close enough to prevent lane changes", isCorrect: false },
      { text: "You brake late but always stop in time", isCorrect: false },
      { text: "You follow closer whenever the examiner is quiet", isCorrect: false },
    ],
  },
];

export const ontarioRoadTestChecklistItems: RoadTestSeedChecklistItem[] = [
  {
    stage: "G2",
    section: "BEFORE_TEST",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#booking-a-road-test`,
    categorySlug: "g2-road-test-readiness",
    title: "Practise full observation routines",
    description: "Before booking, make mirror checks, blind-spot checks, signals, and left-right scans automatic at every turn, lane change, stop, and parking move.",
    sortOrder: 10,
  },
  {
    stage: "G2",
    section: "BEFORE_TEST",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#parallel-parking`,
    categorySlug: "g2-turns-parking-and-control",
    title: "Rehearse parking and roadside stops",
    description: "Practise parallel parking, hill parking, roadside stops, and safe pull-outs until you can do them slowly with full traffic checks.",
    sortOrder: 20,
  },
  {
    stage: "G2",
    section: "DURING_TEST",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#turning-a-corner`,
    categorySlug: "g2-observation-and-right-of-way",
    title: "Slow before every turn",
    description: "Finish braking before the turn, scan for pedestrians and traffic, check blind spots where needed, then accelerate only after the vehicle is straight and safe.",
    sortOrder: 30,
  },
  {
    stage: "G2",
    section: "DURING_TEST",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#changing-lanes`,
    categorySlug: "g2-observation-and-right-of-way",
    title: "Make lane changes obvious and calm",
    description: "The examiner should see a mirror check, signal, blind-spot check, safe gap selection, smooth steering, and stable speed before and during each lane change.",
    sortOrder: 40,
  },
  {
    stage: "G2",
    section: "COMMON_FAIL_REASONS",
    sourceReference: `${ontarioRoadTestSourceUrls.changingDirections}#left-turns`,
    categorySlug: "g2-observation-and-right-of-way",
    title: "Do not force left turns",
    description: "A left turn becomes unsafe when you rush across oncoming traffic, miss pedestrians, turn wide, or move before the path is clearly open.",
    sortOrder: 50,
  },
  {
    stage: "G2",
    section: "COMMON_FAIL_REASONS",
    sourceReference: `${ontarioRoadTestSourceUrls.parking}#roadside-stop`,
    categorySlug: "g2-turns-parking-and-control",
    title: "Avoid unsafe pull-outs",
    description: "Pulling away from the curb without signalling, mirror checks, blind-spot checks, and a safe traffic gap can create an immediate road-test safety problem.",
    sortOrder: 60,
  },
  {
    stage: "G2",
    section: "SELF_ASSESSMENT",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#g2-road-test-g1-exit-test`,
    categorySlug: "g2-road-test-readiness",
    title: "Pass three mock G2 routes",
    description: "Before booking, complete at least three mock routes with no rolling stops, missed blind spots, rushed turns, curb hits, or instructor safety interventions.",
    sortOrder: 70,
  },
  {
    stage: "G2",
    section: "SELF_ASSESSMENT",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#what-happens-if-i-fail-a-g1-or-g2-road-test`,
    categorySlug: "g2-road-test-readiness",
    title: "Recover calmly from mistakes",
    description: "A ready driver can correct a small positioning or timing mistake without panic, argument, speeding, or making a second unsafe move.",
    sortOrder: 80,
  },
  {
    stage: "G",
    section: "BEFORE_TEST",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#g-road-test-g2-exit-test`,
    categorySlug: "g-road-test-readiness",
    title: "Practise highway comfort before booking",
    description: "Book the full G only when freeway merging, lane changes, following distance, and exits feel routine in normal traffic, not brand new.",
    sortOrder: 110,
  },
  {
    stage: "G",
    section: "BEFORE_TEST",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    title: "Rehearse merge and exit sequences",
    description: "Practise acceleration-lane speed matching, signalling, blind-spot checks, safe gap selection, exit planning, and ramp-speed control as one repeatable sequence.",
    sortOrder: 120,
  },
  {
    stage: "G",
    section: "DURING_TEST",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#entering-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    title: "Use the acceleration lane fully",
    description: "On the test, build appropriate speed, keep checking mirrors and blind spots, and merge only into a safe gap without surprising freeway traffic.",
    sortOrder: 130,
  },
  {
    stage: "G",
    section: "DURING_TEST",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#lane-change`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    title: "Keep lane changes smooth",
    description: "A full-G lane change should show planning, signal timing, mirror and shoulder checks, stable speed, and a smooth move into open space.",
    sortOrder: 140,
  },
  {
    stage: "G",
    section: "COMMON_FAIL_REASONS",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#leaving-a-freeway`,
    categorySlug: "g-highway-merging-and-exiting",
    title: "Do not make last-second exits",
    description: "Crossing lanes late, braking suddenly in through traffic, or trying to recover a missed exit can be more dangerous than simply continuing safely.",
    sortOrder: 150,
  },
  {
    stage: "G",
    section: "COMMON_FAIL_REASONS",
    sourceReference: `${ontarioRoadTestSourceUrls.freewayDriving}#driving-along-a-freeway`,
    categorySlug: "g-advanced-lane-and-traffic-flow",
    title: "Avoid cutting off traffic",
    description: "At freeway speeds, small gaps disappear quickly. Do not merge, pass, or change lanes unless another driver can maintain speed and space safely.",
    sortOrder: 160,
  },
  {
    stage: "G",
    section: "SELF_ASSESSMENT",
    sourceReference: `${ontarioRoadTestSourceUrls.levelTwoRoadTest}#freeway`,
    categorySlug: "g-road-test-readiness",
    title: "Complete three highway mock drives",
    description: "Before booking, complete at least three practice drives with safe merges, lane changes, exits, spacing, and speed control without instructor intervention.",
    sortOrder: 170,
  },
  {
    stage: "G",
    section: "SELF_ASSESSMENT",
    sourceReference: `${ontarioRoadTestSourceUrls.newDrivers}#what-happens-if-i-fail-a-g1-or-g2-road-test`,
    categorySlug: "g-road-test-readiness",
    title: "Missed exit recovery is safe",
    description: "A ready full-G driver can miss a turn or exit and continue legally without abrupt braking, shoulder use, reversing, or unsafe multi-lane moves.",
    sortOrder: 180,
  },
];

export function getOntarioRoadTestSeedSummary() {
  const questionCountsByStage = ontarioRoadTestSeedQuestions.reduce<Record<LicenseStage, number>>((acc, question) => {
    acc[question.stage] += 1;
    return acc;
  }, { G1: 0, G2: 0, G: 0 });
  const checklistCountsByStage = ontarioRoadTestChecklistItems.reduce<Record<LicenseStage, number>>((acc, item) => {
    acc[item.stage] += 1;
    return acc;
  }, { G1: 0, G2: 0, G: 0 });

  return {
    categoryCount: ontarioRoadTestSeedCategories.length,
    questionCount: ontarioRoadTestSeedQuestions.length,
    checklistCount: ontarioRoadTestChecklistItems.length,
    sourceCount: Object.keys(ontarioRoadTestSourceUrls).length,
    questionCountsByStage,
    checklistCountsByStage,
  };
}
