export type SeedCategory = {
  slug: string;
  name: string;
  description: string;
  sortOrder: number;
};

export type SeedQuestionChoice = {
  text: string;
  isCorrect: boolean;
};

export type SeedRoadSignAsset = {
  slug: string;
  title: string;
  filename: string;
  path: string;
  mimeType: "image/svg+xml";
  sizeBytes: number;
  description: string;
  sourceCredit: string;
};

export type SeedQuestion = {
  sourceReference: string;
  categorySlug: string;
  prompt: string;
  explanation: string;
  assetSlugs?: string[];
  choices: SeedQuestionChoice[];
};

export const ontarioG1SourceUrls = {
  signsAndLights: "https://www.ontario.ca/document/official-mto-drivers-handbook/traffic-signs-and-lights",
  intersections: "https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections",
  sharingRoad: "https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users",
  safeDriving: "https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving",
  changingDirections: "https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions",
  freewayDriving: "https://www.ontario.ca/document/official-mto-drivers-handbook/freeway-driving",
  parking: "https://www.ontario.ca/document/official-mto-drivers-handbook/parking-along-roadways",
  nightBadWeather: "https://www.ontario.ca/document/official-mto-drivers-handbook/driving-night-and-bad-weather",
} as const;

export const ontarioG1SeedCategories: SeedCategory[] = [
  {
    slug: "g1-signs-and-lights",
    name: "Signs and traffic lights",
    description: "Regulatory signs, warning signs, lane-use signals, and traffic lights from the Ontario driver handbook.",
    sortOrder: 10,
  },
  {
    slug: "g1-right-of-way",
    name: "Intersections and right-of-way",
    description: "Controlled and uncontrolled intersections, stop signs, yield rules, turns, and pedestrian crossovers.",
    sortOrder: 20,
  },
  {
    slug: "g1-sharing-the-road",
    name: "Sharing the road",
    description: "Pedestrians, cyclists, school buses, emergency vehicles, and other road users.",
    sortOrder: 30,
  },
  {
    slug: "g1-safe-driving",
    name: "Safe driving basics",
    description: "Following distance, signalling, blind spots, seat belts, and responsible driving habits.",
    sortOrder: 40,
  },
  {
    slug: "g1-special-conditions",
    name: "Special conditions",
    description: "Railway crossings, night driving, bad weather, and reduced visibility.",
    sortOrder: 50,
  },
  {
    slug: "g1-turns-and-lane-changes",
    name: "Turns and lane changes",
    description: "Safe turning, signalling, lane changes, passing, and roundabout decisions from the Ontario driver handbook.",
    sortOrder: 60,
  },
  {
    slug: "g1-freeway-and-highway",
    name: "Freeway and highway basics",
    description: "Entering, driving on, and leaving freeways, including lane discipline and HOV lane awareness.",
    sortOrder: 70,
  },
  {
    slug: "g1-parking",
    name: "Parking and roadside stops",
    description: "Parallel parking, hill parking, roadside stops, disabled parking spaces, and safe door checks.",
    sortOrder: 80,
  },
];

export const ontarioG1RoadSignAssets: SeedRoadSignAsset[] = [
  {
    slug: "ontario-stop",
    title: "Stop sign",
    filename: "ontario-stop.svg",
    path: "/uploads/road-signs/ontario-stop.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 4981,
    description: "Ontario stop sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Ra-001.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-yield",
    title: "Yield sign",
    filename: "ontario-yield.svg",
    path: "/uploads/road-signs/ontario-yield.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 5286,
    description: "Ontario yield sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Ra-002.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-maximum-40",
    title: "Maximum 40 km/h sign",
    filename: "ontario-maximum-40.svg",
    path: "/uploads/road-signs/ontario-maximum-40.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 11324,
    description: "Ontario maximum 40 sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-001-040.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-maximum-50",
    title: "Maximum 50 km/h sign",
    filename: "ontario-maximum-50.svg",
    path: "/uploads/road-signs/ontario-maximum-50.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 10552,
    description: "Ontario maximum 50 sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-001-050.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-maximum-60",
    title: "Maximum 60 km/h sign",
    filename: "ontario-maximum-60.svg",
    path: "/uploads/road-signs/ontario-maximum-60.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 12997,
    description: "Ontario maximum 60 sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-001-060.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-maximum-80",
    title: "Maximum 80 km/h sign",
    filename: "ontario-maximum-80.svg",
    path: "/uploads/road-signs/ontario-maximum-80.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 14225,
    description: "Ontario maximum 80 sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-001-080.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-maximum-100",
    title: "Maximum 100 km/h sign",
    filename: "ontario-maximum-100.svg",
    path: "/uploads/road-signs/ontario-maximum-100.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 15659,
    description: "Ontario maximum 100 sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-001-100.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-speed-fines-50",
    title: "Speed fines sign",
    filename: "ontario-speed-fines-50.svg",
    path: "/uploads/road-signs/ontario-speed-fines-50.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 8367,
    description: "Ontario speed fines sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-005-50.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-school-crossing",
    title: "School crossing sign",
    filename: "ontario-school-crossing.svg",
    path: "/uploads/road-signs/ontario-school-crossing.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 6085,
    description: "Ontario school crossing sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Wc-002.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-pedestrian-crossover",
    title: "Pedestrian crossover sign",
    filename: "ontario-pedestrian-crossover.svg",
    path: "/uploads/road-signs/ontario-pedestrian-crossover.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 37493,
    description: "Ontario pedestrian crossover sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Ra-008 (B).svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-railway-crossing",
    title: "Railway crossing ahead sign",
    filename: "ontario-railway-crossing.svg",
    path: "/uploads/road-signs/ontario-railway-crossing.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 4028,
    description: "Ontario railway crossing sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "Ontario Wc-4.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-one-way",
    title: "One way sign",
    filename: "ontario-one-way.svg",
    path: "/uploads/road-signs/ontario-one-way.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 7872,
    description: "Ontario one way sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-048.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-no-left-turn",
    title: "No left turn sign",
    filename: "ontario-no-left-turn.svg",
    path: "/uploads/road-signs/ontario-no-left-turn.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 9954,
    description: "Ontario no left turn sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-079-L.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-no-right-turn",
    title: "No right turn sign",
    filename: "ontario-no-right-turn.svg",
    path: "/uploads/road-signs/ontario-no-right-turn.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 9934,
    description: "Ontario no right turn sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-079-R.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-do-not-enter",
    title: "Do not enter sign",
    filename: "ontario-do-not-enter.svg",
    path: "/uploads/road-signs/ontario-do-not-enter.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 3814,
    description: "Ontario do not enter sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-019.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-no-stopping",
    title: "No stopping sign",
    filename: "ontario-no-stopping.svg",
    path: "/uploads/road-signs/ontario-no-stopping.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 22314,
    description: "Ontario no stopping sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-010A (B).svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-no-u-turn",
    title: "No U-turn sign",
    filename: "ontario-no-u-turn.svg",
    path: "/uploads/road-signs/ontario-no-u-turn.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 7292,
    description: "Ontario no U-turn sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-011.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-no-left-turn-alt",
    title: "Turn restriction sign",
    filename: "ontario-no-left-turn-alt.svg",
    path: "/uploads/road-signs/ontario-no-left-turn-alt.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 7372,
    description: "Ontario turn restriction sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Rb-012.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-yield-ahead",
    title: "Yield ahead sign",
    filename: "ontario-yield-ahead.svg",
    path: "/uploads/road-signs/ontario-yield-ahead.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 5751,
    description: "Ontario yield ahead sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Wb-001A.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
  {
    slug: "ontario-keep-right",
    title: "Keep right sign",
    filename: "ontario-keep-right.svg",
    path: "/uploads/road-signs/ontario-keep-right.svg",
    mimeType: "image/svg+xml",
    sizeBytes: 3716,
    description: "Ontario keep right sign from Wikimedia Commons for G1 road-sign practice.",
    sourceCredit: "CA-ON road sign Ra-005-R.svg; Government of Ontario / Ministry of Transportation; Public domain via Wikimedia Commons.",
  },
];

export const ontarioG1SeedQuestions: SeedQuestion[] = [
  {
    sourceReference: `${ontarioG1SourceUrls.intersections}#controlled-intersections`,
    categorySlug: "g1-right-of-way",
    prompt: "At a stop sign, what must you do before entering the intersection?",
    explanation: "Ontario's handbook treats stop signs as controlled intersections. You must come to a complete stop, check for pedestrians and traffic, yield the right-of-way where required, and proceed only when it is safe.",
    assetSlugs: ["ontario-stop"],
    choices: [
      { text: "Come to a complete stop, yield where required, and proceed only when safe", isCorrect: true },
      { text: "Slow down only if another vehicle is already in the intersection", isCorrect: false },
      { text: "Stop only when turning left", isCorrect: false },
      { text: "Honk and continue if you arrived first", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.intersections}#controlled-intersections`,
    categorySlug: "g1-right-of-way",
    prompt: "When two vehicles arrive at an all-way stop at the same time, who should go first?",
    explanation: "When vehicles reach an all-way stop at the same time, the driver on the left should yield to the driver on the right. You should still make sure the way is clear before moving.",
    choices: [
      { text: "The driver on the right", isCorrect: true },
      { text: "The driver turning left", isCorrect: false },
      { text: "The faster vehicle", isCorrect: false },
      { text: "The driver who honks first", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.intersections}#controlled-intersections`,
    categorySlug: "g1-right-of-way",
    prompt: "What does a yield sign require you to do?",
    explanation: "A yield sign means you must slow down or stop if necessary and give the right-of-way to traffic and pedestrians before proceeding.",
    assetSlugs: ["ontario-yield"],
    choices: [
      { text: "Slow or stop if needed and give the right-of-way before proceeding", isCorrect: true },
      { text: "Speed up to merge ahead of other traffic", isCorrect: false },
      { text: "Stop for exactly three seconds every time", isCorrect: false },
      { text: "Only yield to vehicles, not pedestrians", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.intersections}#controlled-intersections`,
    categorySlug: "g1-right-of-way",
    prompt: "At an uncontrolled intersection, what should you do?",
    explanation: "At uncontrolled intersections, slow down, look carefully for pedestrians, cyclists and vehicles, and be ready to yield. If another vehicle arrives at the same time, yield to the vehicle on your right.",
    choices: [
      { text: "Slow down, scan all directions, and yield where required", isCorrect: true },
      { text: "Assume traffic on the larger road always stops", isCorrect: false },
      { text: "Drive through without slowing if there are no signs", isCorrect: false },
      { text: "Only look left before entering", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.intersections}#pedestrian-crossovers`,
    categorySlug: "g1-right-of-way",
    prompt: "At a pedestrian crossover, when may you proceed?",
    explanation: "Ontario's handbook says drivers must yield and wait for pedestrians to completely cross the road at pedestrian crossovers and school crossings with crossing guards before proceeding.",
    assetSlugs: ["ontario-pedestrian-crossover"],
    choices: [
      { text: "After pedestrians have completely crossed the road", isCorrect: true },
      { text: "As soon as pedestrians pass your lane", isCorrect: false },
      { text: "After waving pedestrians to hurry", isCorrect: false },
      { text: "Whenever the vehicle behind you honks", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#traffic-lights`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What should you do at a steady red traffic light?",
    explanation: "A steady red light means stop. Stop before the stop line, crosswalk or intersection, and remain stopped until the signal changes and the way is clear.",
    choices: [
      { text: "Stop before the stop line, crosswalk or intersection", isCorrect: true },
      { text: "Continue if no police officer is present", isCorrect: false },
      { text: "Slow down and continue if the road looks empty", isCorrect: false },
      { text: "Stop only if turning left", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#traffic-lights`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What does a flashing red traffic light mean?",
    explanation: "A flashing red light should be treated like a stop sign: stop completely, yield the right-of-way, and proceed only when safe.",
    choices: [
      { text: "Stop completely, yield, and proceed only when safe", isCorrect: true },
      { text: "Drive through because cross traffic has a flashing yellow", isCorrect: false },
      { text: "Slow down but do not stop", isCorrect: false },
      { text: "Stop only if another vehicle is visible", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#traffic-lights`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What does a flashing yellow traffic light tell you?",
    explanation: "A flashing yellow light warns you to slow down, drive with caution, and be prepared to stop if necessary.",
    choices: [
      { text: "Slow down and proceed with caution", isCorrect: true },
      { text: "Stop and wait until it turns green", isCorrect: false },
      { text: "Speed up to clear the intersection", isCorrect: false },
      { text: "Treat it as a four-way stop every time", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What is the purpose of regulatory signs such as stop, yield, and speed-limit signs?",
    explanation: "Regulatory signs tell drivers about traffic laws and must be obeyed. They are not just suggestions or warnings.",
    assetSlugs: ["ontario-stop", "ontario-yield", "ontario-maximum-50"],
    choices: [
      { text: "They tell drivers about rules that must be obeyed", isCorrect: true },
      { text: "They only give optional route advice", isCorrect: false },
      { text: "They apply only during rush hour", isCorrect: false },
      { text: "They are used only on highways", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#warning-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What do warning signs generally tell you?",
    explanation: "Warning signs alert drivers to hazards or changes ahead, such as curves, crossings, merging traffic, or road conditions, so drivers can adjust speed and position early.",
    choices: [
      { text: "A hazard or road condition is ahead", isCorrect: true },
      { text: "You must always stop immediately", isCorrect: false },
      { text: "The road is closed to all traffic", isCorrect: false },
      { text: "The sign applies only to trucks", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.sharingRoad}#sharing-the-road-with-school-buses`,
    categorySlug: "g1-sharing-the-road",
    prompt: "When a school bus has overhead amber lights flashing, what should nearby drivers do?",
    explanation: "The Ontario handbook says flashing amber lights mean the bus is preparing to stop to pick up or drop off passengers. Drivers should slow down and prepare to stop.",
    assetSlugs: ["ontario-school-crossing"],
    choices: [
      { text: "Slow down and prepare to stop", isCorrect: true },
      { text: "Pass quickly before the bus stops", isCorrect: false },
      { text: "Ignore the bus unless the stop arm is out", isCorrect: false },
      { text: "Stop only if you are directly behind the bus", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.sharingRoad}#sharing-the-road-with-school-buses`,
    categorySlug: "g1-sharing-the-road",
    prompt: "When a school bus is stopped with red lights flashing, what must drivers approaching from either direction generally do?",
    explanation: "Drivers must stop for a school bus with red lights flashing when approaching from the front or rear, unless they are on the opposite side of a road divided by a median strip.",
    assetSlugs: ["ontario-school-crossing"],
    choices: [
      { text: "Stop and remain stopped until the bus lights stop flashing or the bus moves", isCorrect: true },
      { text: "Pass slowly if no children are visible", isCorrect: false },
      { text: "Stop only behind the bus, never when approaching from the front", isCorrect: false },
      { text: "Honk before passing", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.sharingRoad}#emergency-vehicles`,
    categorySlug: "g1-sharing-the-road",
    prompt: "What should you do when an emergency vehicle approaches with siren or flashing lights?",
    explanation: "Move safely to the right and stop to let emergency vehicles pass. Do not block intersections, and check that the way is clear before moving again.",
    choices: [
      { text: "Move safely to the right and stop", isCorrect: true },
      { text: "Speed up to stay ahead of it", isCorrect: false },
      { text: "Stop in the middle of an intersection", isCorrect: false },
      { text: "Follow closely behind it through traffic", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.sharingRoad}#sharing-the-road-with-cyclists`,
    categorySlug: "g1-sharing-the-road",
    prompt: "Why should drivers check blind spots before turning or changing lanes near cyclists?",
    explanation: "Cyclists can be hard to see and may be beside or behind a vehicle. Checking mirrors and blind spots helps prevent cutting off or striking a cyclist.",
    choices: [
      { text: "Cyclists may be beside the vehicle where mirrors do not show them clearly", isCorrect: true },
      { text: "Cyclists always have to stop when cars turn", isCorrect: false },
      { text: "Blind spots matter only on expressways", isCorrect: false },
      { text: "Cyclists are required to ride only on sidewalks", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.safeDriving}#space`,
    categorySlug: "g1-safe-driving",
    prompt: "What is the two-second rule used for?",
    explanation: "The two-second rule is a simple way to check that you are leaving enough following distance from the vehicle ahead in normal conditions. More space is needed in poor weather or low visibility.",
    choices: [
      { text: "Checking a safe following distance", isCorrect: true },
      { text: "Timing how long to stop at every stop sign", isCorrect: false },
      { text: "Measuring how long to signal before every turn", isCorrect: false },
      { text: "Deciding when to shift gears", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.safeDriving}#signalling`,
    categorySlug: "g1-safe-driving",
    prompt: "Why should you signal well before turning or changing lanes?",
    explanation: "Signals tell other road users what you intend to do. Signalling early gives drivers, cyclists, and pedestrians time to react, but it does not give you the right-of-way by itself.",
    choices: [
      { text: "To warn other road users of your intentions before you move", isCorrect: true },
      { text: "Because signalling automatically gives you the right-of-way", isCorrect: false },
      { text: "Only to warn police officers", isCorrect: false },
      { text: "Only when another vehicle is directly behind you", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.safeDriving}#seatbelts`,
    categorySlug: "g1-safe-driving",
    prompt: "Who must wear a seat belt in a vehicle where seat belts are provided?",
    explanation: "Seat belts save lives and are required where provided. Drivers are responsible for making sure passengers under 16 are properly secured.",
    choices: [
      { text: "The driver and passengers where seat belts are provided", isCorrect: true },
      { text: "Only the driver", isCorrect: false },
      { text: "Only front-seat passengers", isCorrect: false },
      { text: "Only passengers under 16", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.safeDriving}#blind-spots`,
    categorySlug: "g1-safe-driving",
    prompt: "Before changing lanes, what should you do in addition to checking your mirrors?",
    explanation: "Mirrors do not show every area around your vehicle. Check your blind spot by looking over your shoulder before changing lanes.",
    choices: [
      { text: "Check your blind spot over your shoulder", isCorrect: true },
      { text: "Assume your mirrors show everything", isCorrect: false },
      { text: "Change lanes first, then signal", isCorrect: false },
      { text: "Rely only on other drivers to make room", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.safeDriving}#railway-crossings`,
    categorySlug: "g1-special-conditions",
    prompt: "At a railway crossing with flashing lights or a lowered gate, what must you do?",
    explanation: "Stop before the railway crossing when warning lights are flashing, gates are lowered, or a train is approaching. Proceed only when the signals stop and it is safe.",
    assetSlugs: ["ontario-railway-crossing"],
    choices: [
      { text: "Stop and wait until it is safe to cross", isCorrect: true },
      { text: "Drive around the gate if the train looks far away", isCorrect: false },
      { text: "Stop on the tracks to get a better view", isCorrect: false },
      { text: "Cross quickly before the gate fully lowers", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.safeDriving}#bad-weather`,
    categorySlug: "g1-special-conditions",
    prompt: "How should you adjust your driving in rain, snow, fog, or other poor conditions?",
    explanation: "Poor weather and reduced visibility require slower speeds, more following distance, smoother braking and steering, and lights when needed so you can see and be seen.",
    choices: [
      { text: "Slow down and leave more space", isCorrect: true },
      { text: "Follow closer so you can see the vehicle ahead", isCorrect: false },
      { text: "Use high beams in thick fog", isCorrect: false },
      { text: "Brake hard whenever traction is low", isCorrect: false },
    ],
  },

  {
    sourceReference: `${ontarioG1SourceUrls.changingDirections}#turning-a-corner`,
    categorySlug: "g1-turns-and-lane-changes",
    prompt: "Before turning a corner, what checks should you make?",
    explanation: "The Ontario handbook tells drivers to signal, look side to side, check blind spots, and make sure the way is clear before entering a turn.",
    choices: [
      { text: "Signal, scan the intersection, check blind spots, and turn only when clear", isCorrect: true },
      { text: "Turn first, then signal if another vehicle appears", isCorrect: false },
      { text: "Check only the mirror on the side you are turning toward", isCorrect: false },
      { text: "Speed up so the turn takes less time", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.changingDirections}#turning-a-corner`,
    categorySlug: "g1-turns-and-lane-changes",
    prompt: "Why should you slow down before entering a turn?",
    explanation: "Slowing before the turn helps you keep full control. The sharper the turn, the slower you should go, and braking should be finished before you steer through the turn.",
    choices: [
      { text: "To keep control and finish braking before steering through the turn", isCorrect: true },
      { text: "Because vehicles must stop during every turn", isCorrect: false },
      { text: "So traffic behind you can pass on either side", isCorrect: false },
      { text: "Because signalling is not needed at low speed", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.changingDirections}#right-turns`,
    categorySlug: "g1-turns-and-lane-changes",
    prompt: "From which lane should you normally make a right turn?",
    explanation: "For a normal right turn, move into the far right lane before turning, signal early, check traffic and pedestrians, and keep the turn controlled.",
    choices: [
      { text: "From the far right lane in your direction of travel", isCorrect: true },
      { text: "From the far left lane whenever traffic is light", isCorrect: false },
      { text: "From any lane if you signal after starting the turn", isCorrect: false },
      { text: "From the oncoming lane to make the turn wider", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.changingDirections}#right-turn-on-a-red-light`,
    categorySlug: "g1-turns-and-lane-changes",
    prompt: "What must you do before turning right on a red light where it is allowed?",
    explanation: "A right turn on red is allowed only where not prohibited. You must stop first, yield to pedestrians and traffic, and proceed only when the way is clear.",
    choices: [
      { text: "Stop first, yield to pedestrians and traffic, then turn only if clear", isCorrect: true },
      { text: "Slow down but keep moving if no car is directly in front", isCorrect: false },
      { text: "Turn right on red even when a sign prohibits it", isCorrect: false },
      { text: "Honk before turning so pedestrians know to stop", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.changingDirections}#changing-lanes`,
    categorySlug: "g1-turns-and-lane-changes",
    prompt: "What is the safe sequence before changing lanes?",
    explanation: "Before changing lanes, check traffic ahead and behind, signal, check mirrors and blind spots, and move only when there is a safe gap.",
    choices: [
      { text: "Check traffic, signal, check mirrors and blind spots, then move when safe", isCorrect: true },
      { text: "Signal only after your vehicle is halfway into the new lane", isCorrect: false },
      { text: "Rely on other drivers to brake and create a gap", isCorrect: false },
      { text: "Change lanes quickly without checking if your speed is higher", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.changingDirections}#passing`,
    categorySlug: "g1-turns-and-lane-changes",
    prompt: "When passing another vehicle, what should guide your decision?",
    explanation: "Passing is safe only when it is legal, the way is clear, and you have enough time and space to return without cutting off the vehicle you passed.",
    choices: [
      { text: "Pass only when legal, clear, and there is enough space to return safely", isCorrect: true },
      { text: "Pass whenever the vehicle ahead is below the speed limit", isCorrect: false },
      { text: "Pass on hills because oncoming drivers can see you sooner", isCorrect: false },
      { text: "Return to the lane immediately in front of the vehicle you passed", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.freewayDriving}#entering-a-freeway`,
    categorySlug: "g1-freeway-and-highway",
    prompt: "What should you do on a freeway acceleration lane?",
    explanation: "Use the acceleration lane to build speed, signal, check traffic and blind spots, and merge into a safe gap without forcing other drivers to brake sharply.",
    choices: [
      { text: "Build speed, signal, check for a safe gap, and merge smoothly", isCorrect: true },
      { text: "Stop at the end of the lane unless traffic is completely empty", isCorrect: false },
      { text: "Merge immediately at low speed to get out of the lane", isCorrect: false },
      { text: "Expect freeway traffic to move aside automatically", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.freewayDriving}#driving-along-a-freeway`,
    categorySlug: "g1-freeway-and-highway",
    prompt: "On a freeway, why is a safe following distance especially important?",
    explanation: "Freeway speeds leave less time to react. Keeping space around your vehicle gives you time to respond to traffic changes and avoid cutting off other drivers.",
    choices: [
      { text: "Higher speeds require more time and space to react safely", isCorrect: true },
      { text: "It lets you drive above the speed limit safely", isCorrect: false },
      { text: "It means you do not need to check mirrors", isCorrect: false },
      { text: "It is only needed when driving in the far left lane", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.freewayDriving}#driving-along-a-freeway`,
    categorySlug: "g1-freeway-and-highway",
    prompt: "Which lane should slower traffic generally use on a multi-lane freeway?",
    explanation: "The handbook directs slower-moving traffic to keep to the right. The far left lane is generally used for passing or faster-moving traffic where allowed.",
    choices: [
      { text: "The right lane", isCorrect: true },
      { text: "The far left lane at all times", isCorrect: false },
      { text: "The shoulder", isCorrect: false },
      { text: "Whichever lane has the most vehicles", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.freewayDriving}#leaving-a-freeway`,
    categorySlug: "g1-freeway-and-highway",
    prompt: "How should you leave a freeway safely?",
    explanation: "Plan ahead for your exit, signal early, move into the exit lane when safe, and slow down mainly in the deceleration lane or ramp rather than in through traffic.",
    choices: [
      { text: "Plan ahead, signal, move safely to the exit lane, and slow on the ramp", isCorrect: true },
      { text: "Brake hard in the through lane when you see the exit", isCorrect: false },
      { text: "Cross several lanes at the last second", isCorrect: false },
      { text: "Reverse on the shoulder if you miss the exit", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.freewayDriving}#high-occupancy-vehicle-hov-lane`,
    categorySlug: "g1-freeway-and-highway",
    prompt: "What should new drivers know about HOV lanes?",
    explanation: "High Occupancy Vehicle lanes have special signs and pavement markings. Drivers must understand the posted rules before using them.",
    choices: [
      { text: "They have special posted rules and markings that must be followed", isCorrect: true },
      { text: "They are open to every vehicle at all times", isCorrect: false },
      { text: "They are only for passing on the right", isCorrect: false },
      { text: "They remove the need to signal lane changes", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.parking}#parking-for-people-with-disabilities`,
    categorySlug: "g1-parking",
    prompt: "When may you park in a space designated for people with disabilities?",
    explanation: "The Ontario handbook says you must not park in an accessible parking space unless the proper Accessible Parking Permit is displayed and belongs to the person using it.",
    choices: [
      { text: "Only when a valid Accessible Parking Permit is properly displayed", isCorrect: true },
      { text: "Whenever the space is empty for less than five minutes", isCorrect: false },
      { text: "If you leave your hazard lights on", isCorrect: false },
      { text: "If you are picking up food or mail quickly", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.parking}#parking-on-a-hill`,
    categorySlug: "g1-parking",
    prompt: "When parking downhill, which way should you turn your front wheels?",
    explanation: "When facing downhill, turn the front wheels toward the curb or right shoulder so the vehicle rolls away from traffic if the brakes fail.",
    choices: [
      { text: "Toward the curb or right shoulder", isCorrect: true },
      { text: "Toward the centre of the road", isCorrect: false },
      { text: "Straight ahead in every situation", isCorrect: false },
      { text: "Whichever way makes it easier to leave", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.parking}#parking-on-a-hill`,
    categorySlug: "g1-parking",
    prompt: "When parking uphill with a curb, which way should you turn your wheels?",
    explanation: "When facing uphill with a curb, turn the steering wheel left so the wheels are turned toward the road and the tires can catch the curb if the vehicle rolls backward.",
    choices: [
      { text: "To the left, toward the road", isCorrect: true },
      { text: "To the right, away from the road", isCorrect: false },
      { text: "Straight ahead", isCorrect: false },
      { text: "Toward the sidewalk at a sharp angle", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.parking}#parking-on-a-hill`,
    categorySlug: "g1-parking",
    prompt: "When parking uphill without a curb, why should you turn the wheels sharply to the right?",
    explanation: "Without a curb, turning the wheels sharply right helps the vehicle roll off the road rather than into traffic if it moves unexpectedly.",
    choices: [
      { text: "So the vehicle would roll off the road instead of into traffic", isCorrect: true },
      { text: "So the vehicle rolls into the nearest lane", isCorrect: false },
      { text: "Because the law requires wheels left in every uphill situation", isCorrect: false },
      { text: "To make the parking brake unnecessary", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.parking}#roadside-stop`,
    categorySlug: "g1-parking",
    prompt: "Before opening your door after a roadside stop, what should you do?",
    explanation: "After stopping at the roadside, check for traffic, cyclists, and pedestrians before opening your door so you do not create a hazard.",
    choices: [
      { text: "Check for traffic, cyclists, and pedestrians before opening it", isCorrect: true },
      { text: "Open it quickly so others know you are parked", isCorrect: false },
      { text: "Only check if you parked beside a bike lane", isCorrect: false },
      { text: "Leave the door partly open as a warning", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.nightBadWeather}#overdriving-your-headlights`,
    categorySlug: "g1-special-conditions",
    prompt: "What does overdriving your headlights mean?",
    explanation: "Overdriving your headlights means travelling so fast that your stopping distance is farther than you can see with your headlights, making it harder to stop for hazards at night.",
    choices: [
      { text: "Driving so fast you cannot stop within the distance your headlights show", isCorrect: true },
      { text: "Using high beams on a rural road", isCorrect: false },
      { text: "Driving with headlights on during daylight", isCorrect: false },
      { text: "Turning headlights off in a well-lit area", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.nightBadWeather}#glare`,
    categorySlug: "g1-special-conditions",
    prompt: "When should you use low-beam headlights around other vehicles at night?",
    explanation: "To reduce glare, use low beams within 150 metres of an oncoming vehicle or when following another vehicle within 60 metres.",
    choices: [
      { text: "Within 150 m of oncoming vehicles or 60 m when following", isCorrect: true },
      { text: "Only after another driver flashes their lights", isCorrect: false },
      { text: "Only on city streets with streetlights", isCorrect: false },
      { text: "Never; high beams are always safer at night", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.nightBadWeather}#fog`,
    categorySlug: "g1-special-conditions",
    prompt: "What is a safe response when fog becomes very thick?",
    explanation: "In heavy fog, slow down, use low-beam headlights, and if visibility becomes too poor, pull well off the road to a safe parking area and use emergency flashers.",
    choices: [
      { text: "Slow down, use low beams, and pull off safely if visibility is too poor", isCorrect: true },
      { text: "Use high beams so the fog reflects more light", isCorrect: false },
      { text: "Stop in the travelled lane until the fog clears", isCorrect: false },
      { text: "Speed up suddenly when the fog appears to thin", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.nightBadWeather}#skids`,
    categorySlug: "g1-special-conditions",
    prompt: "How can you reduce the risk of skidding on a slippery road?",
    explanation: "Most skids happen when drivers go too fast for conditions or use harsh braking, steering, or acceleration. Reduce speed and use smooth, controlled inputs.",
    choices: [
      { text: "Drive slower and use smooth braking, steering, and acceleration", isCorrect: true },
      { text: "Brake hard whenever the vehicle starts to slide", isCorrect: false },
      { text: "Accelerate quickly to regain traction", isCorrect: false },
      { text: "Steer aggressively to force the vehicle back into line", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What does this sign tell a driver to do?",
    explanation: "A stop sign requires a complete stop before the stop line, crosswalk, or intersection. Proceed only after yielding and checking that it is safe.",
    assetSlugs: ["ontario-stop"],
    choices: [
      { text: "Come to a complete stop and proceed only when safe", isCorrect: true },
      { text: "Slow down only if cross traffic is present", isCorrect: false },
      { text: "Yield without stopping every time", isCorrect: false },
      { text: "Continue if the road appears clear", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What does this sign require you to do?",
    explanation: "A yield sign means slow down or stop if necessary and give the right-of-way to traffic and pedestrians before entering or crossing.",
    assetSlugs: ["ontario-yield"],
    choices: [
      { text: "Slow or stop if needed and yield the right-of-way", isCorrect: true },
      { text: "Stop for exactly three seconds no matter what", isCorrect: false },
      { text: "Speed up to merge first", isCorrect: false },
      { text: "Only yield to large trucks", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What does the number shown on this sign mean?",
    explanation: "A maximum speed sign shows the highest legal speed in kilometres per hour under ideal conditions. Drivers must go slower when conditions require it.",
    assetSlugs: ["ontario-maximum-50"],
    choices: [
      { text: "The maximum legal speed is 50 km/h when conditions allow", isCorrect: true },
      { text: "The minimum speed is 50 km/h", isCorrect: false },
      { text: "The recommended ramp speed is 50 km/h", isCorrect: false },
      { text: "Only trucks must obey 50 km/h", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#warning-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What should this sign make you prepare for?",
    explanation: "A school crossing sign warns that children may be crossing nearby. Slow down, scan carefully, and be ready to stop.",
    assetSlugs: ["ontario-school-crossing"],
    choices: [
      { text: "Children or pedestrians may be crossing; slow down and be ready to stop", isCorrect: true },
      { text: "A school bus lane begins and cars must enter it", isCorrect: false },
      { text: "The road is closed to all traffic", isCorrect: false },
      { text: "Only school buses may use the road", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "At the crossing shown by this sign, when may you proceed?",
    explanation: "At pedestrian crossovers, drivers must yield and wait until pedestrians have completely crossed before proceeding.",
    assetSlugs: ["ontario-pedestrian-crossover"],
    choices: [
      { text: "After pedestrians have completely crossed the road", isCorrect: true },
      { text: "As soon as pedestrians pass the front of your vehicle", isCorrect: false },
      { text: "When the driver behind you honks", isCorrect: false },
      { text: "If you wave pedestrians to wait", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#warning-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What hazard is this sign warning about?",
    explanation: "A railway crossing warning sign means train tracks are ahead. Slow down, look and listen, and obey any lights, gates, or signals.",
    assetSlugs: ["ontario-railway-crossing"],
    choices: [
      { text: "A railway crossing is ahead", isCorrect: true },
      { text: "A one-way street begins", isCorrect: false },
      { text: "A school zone ends", isCorrect: false },
      { text: "A divided highway starts", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What does this sign tell you about the road?",
    explanation: "A one-way sign means traffic on that road travels only in the direction shown by the arrow.",
    assetSlugs: ["ontario-one-way"],
    choices: [
      { text: "Traffic travels only in the direction of the arrow", isCorrect: true },
      { text: "You may drive either direction if the lane is clear", isCorrect: false },
      { text: "Only bicycles may use the road", isCorrect: false },
      { text: "The lane is for emergency vehicles only", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What left-turn movement is prohibited by this sign?",
    explanation: "A no-left-turn sign means drivers must not turn left at that location. Choose a legal alternate route.",
    assetSlugs: ["ontario-no-left-turn"],
    choices: [
      { text: "Turning left", isCorrect: true },
      { text: "Turning right", isCorrect: false },
      { text: "Driving straight through", isCorrect: false },
      { text: "Stopping at the intersection", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What right-turn movement is prohibited by this sign?",
    explanation: "A no-right-turn sign means drivers must not turn right at that location, including when a red-light right turn might otherwise be allowed.",
    assetSlugs: ["ontario-no-right-turn"],
    choices: [
      { text: "Turning right", isCorrect: true },
      { text: "Turning left", isCorrect: false },
      { text: "Driving straight through", isCorrect: false },
      { text: "Yielding to pedestrians", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What does this sign mean?",
    explanation: "A do-not-enter sign marks a road or ramp that traffic must not enter from your direction.",
    assetSlugs: ["ontario-do-not-enter"],
    choices: [
      { text: "Do not enter this road or ramp", isCorrect: true },
      { text: "Stop only if another vehicle is coming", isCorrect: false },
      { text: "The road is one way in your direction", isCorrect: false },
      { text: "Parking is allowed ahead", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What movement does this sign prohibit?",
    explanation: "A no-U-turn sign means you must not reverse direction with a U-turn at that location.",
    assetSlugs: ["ontario-no-u-turn"],
    choices: [
      { text: "Making a U-turn", isCorrect: true },
      { text: "Turning right", isCorrect: false },
      { text: "Parking beside the curb", isCorrect: false },
      { text: "Proceeding through the intersection", isCorrect: false },
    ],
  },
  {
    sourceReference: `${ontarioG1SourceUrls.signsAndLights}#regulatory-signs`,
    categorySlug: "g1-signs-and-lights",
    prompt: "What should you do when this sign is posted at an obstruction or traffic island?",
    explanation: "A keep-right sign directs drivers to pass to the right side of the sign or obstruction.",
    assetSlugs: ["ontario-keep-right"],
    choices: [
      { text: "Keep to the right of the sign or obstruction", isCorrect: true },
      { text: "Turn left before the sign", isCorrect: false },
      { text: "Stop and wait for a flag person", isCorrect: false },
      { text: "Drive on either side", isCorrect: false },
    ],
  },
];

export function getOntarioG1SeedSummary() {
  return {
    categoryCount: ontarioG1SeedCategories.length,
    questionCount: ontarioG1SeedQuestions.length,
    sourceCount: Object.keys(ontarioG1SourceUrls).length,
  };
}
