import Link from "next/link";
import { BookOpenCheck, Car, ClipboardCheck, Gauge } from "lucide-react";
import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
const features = [
  { title: "G1 practice", description: "Road signs, rules, safe driving, penalties, and sharing the road.", icon: BookOpenCheck },
  { title: "G2 road-test prep", description: "Before-test checklists, common fail reasons, and guided practice.", icon: Car },
  { title: "Full G readiness", description: "Highway and advanced driving prep with clear next steps.", icon: ClipboardCheck },
  { title: "Progress dashboard", description: "Daily goals, readiness score, weak areas, and mistake review after registration.", icon: Gauge },
];
export default function Home() { return <><SiteHeader /><main className="flex-1"><section className="mx-auto grid max-w-6xl gap-10 px-4 py-16 md:grid-cols-[1.1fr_0.9fr] md:py-24"><div className="space-y-6"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-green-800">Ontario G1 → G2 → G</p><h1 className="text-4xl font-bold tracking-tight text-slate-950 md:text-6xl">A clearer way to prepare for your Ontario driving exam.</h1><p className="max-w-2xl text-lg leading-8 text-slate-600">drivexam is a trustworthy learning companion with realistic practice, plain-English explanations, daily goals, and road-test prep from G1 to full G.</p><div className="flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><Link href="/sign-up">Start studying free</Link></Button><Button asChild size="lg" variant="outline"><Link href="/dashboard">View dashboard preview</Link></Button></div></div><Card className="bg-green-950 text-white"><CardHeader><CardTitle>Your study path</CardTitle></CardHeader><CardContent className="space-y-4 text-green-50"><div className="rounded-xl bg-white/10 p-4"><strong>1. Choose your stage</strong><p>G1, G2, or full G.</p></div><div className="rounded-xl bg-white/10 p-4"><strong>2. Set your test date</strong><p>drivexam recommends daily lessons and questions.</p></div><div className="rounded-xl bg-white/10 p-4"><strong>3. Improve weak areas</strong><p>Review mistakes, road signs, and readiness scores.</p></div></CardContent></Card></section><section className="mx-auto grid max-w-6xl gap-4 px-4 pb-16 md:grid-cols-4">{features.map((feature) => <Card key={feature.title}><CardHeader><feature.icon className="h-8 w-8 text-green-800" /><CardTitle className="text-xl">{feature.title}</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-slate-600">{feature.description}</CardContent></Card>)}</section></main><SiteFooter /></>; }
